### ISSUE TITLE
postrecoveryboot.sh working?

### ISSUE THREAD

**Issue by robaho** [PeterCassetta/android_device_lge_fx3t#2]
Does this code actually prevent the wipe when booting to recovery via adb/app ?

Thanks @PeterCassetta for your work.

**Comment by PeterCassetta** [comment]
Hi @robaho, when testing the current code I never experienced data wipes when booting into CWM recovery via adb or an app like ROM Manager. I believe it also prevents data wipes from occurring when first flashing CWM recovery, but I'm not positive on that.

**Comment by robaho** [comment]
Hmmm, trying on a Virgin Mobile ls720 and I am having it wipe each time...

I noticed some of the code is commented out, is the dd command the only thing required? I realize the VM might have a different misc partition layout... ugh.

**Comment by PeterCassetta** [comment]
@robaho, not sure, then. It's quite possible that this wouldn't work even on a device as similar as the ls720.

Most of the code in this file was written by @PlayfulGod, so I'd recommend you get in touch with him. He has experience with a bunch of different LG devices; maybe he'd be able shed some more light on the subject.

**Comment by robaho** [comment]
Thanks. I'll get in touch with him.

**Comment by playfulgod** [comment]
Most of the other code was experiments with others code I found. @robaho your misc may very well be laid out differently. I found that offset etc by booting to cwm and hexdumping misc, then looking thru the dump for references to recovery and wipe data. Nothing I have tried on the fx3mt has worked to prevent the data wipe, tho I've not hand a F3 in hand to do alot of testing with. The LG Motion has the issue.

GameTheory on AF said it didnt wipe data if using the button combo on the fx3mt.

Oh and the first cmd comment out was what I used on the LG Motion (l0) to fix data that gets corrupted by the wipe booting into recovery as its unmountable otherwise.

**Comment by robaho** [comment]
Yes, the button combo works on the fx3s but it's a pain. 

It seems that the boot loader destroys the data partition before it calls recovery, not after the recovery runs.

**Comment by playfulgod** [comment]
exactly!!!! ;)

**Comment by robaho** [comment]
Obviously there must be someway to disable it because when it boots into stock recovery for updates it doesn't trash the data partition. But I am thinking another possibility is that it does trash it but the stock recovery knows how to fix it.

**Comment by playfulgod** [comment]
my guess is it only fubars a few bytes at the beginning of the partition only if it doesnt find something its looking for. most likely in the recovery partition. We might need to dig thru the stock recovery more to see.

**Comment by lgrootnoob** [comment]
hello, im dealing with the same issue.
as you can see in my repository https://github.com/lgrootnoob/android_device_lge_l1v
i dont think postrecoveryboot is actually running. but if i run the dd command from adb and kill the recovery process it starts up the menu

**Comment by lgrootnoob** [comment]
We have some options. Move /data to the sdcard,
Or dump /data while its live, then dump it in cwm and compare what bytes have changed.
Then write a reboot application that dumps those bytes before reboot into cwm so cwm can restore the bytes when it boots.
